### ISSUE TITLE
Key unable to be pressed before score enabled

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2023-Roots#2]
Key should be able to be pressed before score enabled to result in an early press

**Comment by scarletoath** [comment]
[completed](https://github.com/scarletoath/GGJ2023-Roots/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/scarletoath/GGJ2023-Roots/commit/9b2574bcade35dbacbd3a85dbc320f0fc868ae0d
