### ISSUE TITLE
Zen mode should show 2 keys instead of 1

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2023-Roots#3]
Zen mode now spawns one key instead of randomizing between 2 keys. Both keys should also not be the same as each other

**Comment by scarletoath** [comment]
[completed](https://github.com/scarletoath/GGJ2023-Roots/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/scarletoath/GGJ2023-Roots/commit/9b2574bcade35dbacbd3a85dbc320f0fc868ae0d
